---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - testvars.yml

  tasks:
    - name: "Include role ansible-role-mariadb"
      include_role:
        name: "ansible-role-mariadb"
