---
driver:
  name: podman
platforms:
  - name: instance
    image: "fauust/docker-ansible:${MOLECULE_DISTRO:-debian-10}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  env:
    ANSIBLE_GATHERING: explicit
    ANSIBLE_FORCE_COLOR: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
